name: Build and Release Blazor Server App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rid: [win-x64, win-x86]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Blazor Server app for ${{ matrix.rid }}
        run: |
          dotnet publish SpeedrunRaceDashboard/SpeedrunRaceDashboard.sln \
            -c Release \
            -r ${{ matrix.rid }} \
            --self-contained true \
            -o publish-${{ matrix.rid }}

      - name: Zip output for ${{ matrix.rid }}
        run: |
          cd publish-${{ matrix.rid }}
          zip -r ../srd-${{ matrix.rid }}.zip .
          cd ..

      - name: Upload ${{ matrix.rid }} release asset
        uses: softprops/action-gh-release@v2
        with:
          files: srd-${{ matrix.rid }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use PAT with `repo` scope
