name: Build and Release Blazor Server App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rid: [win-x64, win-x86]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Get latest release tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          version=$(echo $latest_tag | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2.\3/')
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Publish Blazor Server app for ${{ matrix.rid }}
        run: |
          dotnet publish SpeedrunRaceDashboard/SpeedrunRaceDashboard.sln \
            -c Release \
            -r ${{ matrix.rid }} \
            --self-contained true \
            -o publish-${{ matrix.rid }}

      - name: Zip output for ${{ matrix.rid }}
        run: |
          cd publish-${{ matrix.rid }}
          zip -r ../srd-${{ matrix.rid }}.zip .
          cd ..

      - name: Create GitHub release and upload ${{ matrix.rid }} asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.new_tag }}
          name: Release ${{ steps.get_latest_tag.outputs.new_tag }}
          files: srd-${{ matrix.rid }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
